import path from "node:path";

import type { Schema } from "./registry-schema";

type ComponentDefinition = Partial<
  Pick<
    Schema,
    | "dependencies"
    | "devDependencies"
    | "registryDependencies"
    | "cssVars"
    | "tailwind"
    | "title"
    | "description"
    | "author"
    | "css"
    | "envVars"
    | "docs"
    | "categories"
    | "meta"
  >
> & {
  name: string;
  path: string;
};

export const components: ComponentDefinition[] = [
  {
    name: "academic-cap",
    path: path.join(__dirname, "../icons/academic-cap.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "adjustments-horizontal",
    path: path.join(__dirname, "../icons/adjustments-horizontal.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "adjustments-vertical",
    path: path.join(__dirname, "../icons/adjustments-vertical.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "archive-box",
    path: path.join(__dirname, "../icons/archive-box.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "archive-box-arrow-down",
    path: path.join(__dirname, "../icons/archive-box-arrow-down.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "archive-box-x-mark",
    path: path.join(__dirname, "../icons/archive-box-x-mark.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-down",
    path: path.join(__dirname, "../icons/arrow-down.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-down-circle",
    path: path.join(__dirname, "../icons/arrow-down-circle.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-down-left",
    path: path.join(__dirname, "../icons/arrow-down-left.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-down-on-square",
    path: path.join(__dirname, "../icons/arrow-down-on-square.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-down-on-square-stack",
    path: path.join(__dirname, "../icons/arrow-down-on-square-stack.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-down-right",
    path: path.join(__dirname, "../icons/arrow-down-right.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-down-tray",
    path: path.join(__dirname, "../icons/arrow-down-tray.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-left",
    path: path.join(__dirname, "../icons/arrow-left.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-left-circle",
    path: path.join(__dirname, "../icons/arrow-left-circle.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-left-end-on-rectangle",
    path: path.join(__dirname, "../icons/arrow-left-end-on-rectangle.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-left-on-rectangle",
    path: path.join(__dirname, "../icons/arrow-left-on-rectangle.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-left-start-on-rectangle",
    path: path.join(__dirname, "../icons/arrow-left-start-on-rectangle.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-long-down",
    path: path.join(__dirname, "../icons/arrow-long-down.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-long-left",
    path: path.join(__dirname, "../icons/arrow-long-left.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-long-right",
    path: path.join(__dirname, "../icons/arrow-long-right.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-long-up",
    path: path.join(__dirname, "../icons/arrow-long-up.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-path",
    path: path.join(__dirname, "../icons/arrow-path.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-path-rounded-square",
    path: path.join(__dirname, "../icons/arrow-path-rounded-square.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-right",
    path: path.join(__dirname, "../icons/arrow-right.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-right-circle",
    path: path.join(__dirname, "../icons/arrow-right-circle.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-right-end-on-rectangle",
    path: path.join(__dirname, "../icons/arrow-right-end-on-rectangle.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-right-on-rectangle",
    path: path.join(__dirname, "../icons/arrow-right-on-rectangle.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-right-start-on-rectangle",
    path: path.join(__dirname, "../icons/arrow-right-start-on-rectangle.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-small-down",
    path: path.join(__dirname, "../icons/arrow-small-down.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-small-left",
    path: path.join(__dirname, "../icons/arrow-small-left.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-small-right",
    path: path.join(__dirname, "../icons/arrow-small-right.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-small-up",
    path: path.join(__dirname, "../icons/arrow-small-up.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-top-right-on-square",
    path: path.join(__dirname, "../icons/arrow-top-right-on-square.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-trending-down",
    path: path.join(__dirname, "../icons/arrow-trending-down.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-trending-up",
    path: path.join(__dirname, "../icons/arrow-trending-up.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-turn-down-left",
    path: path.join(__dirname, "../icons/arrow-turn-down-left.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-turn-down-right",
    path: path.join(__dirname, "../icons/arrow-turn-down-right.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-turn-left-down",
    path: path.join(__dirname, "../icons/arrow-turn-left-down.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-turn-left-up",
    path: path.join(__dirname, "../icons/arrow-turn-left-up.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-turn-right-down",
    path: path.join(__dirname, "../icons/arrow-turn-right-down.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-turn-right-up",
    path: path.join(__dirname, "../icons/arrow-turn-right-up.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-turn-up-left",
    path: path.join(__dirname, "../icons/arrow-turn-up-left.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-turn-up-right",
    path: path.join(__dirname, "../icons/arrow-turn-up-right.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-up",
    path: path.join(__dirname, "../icons/arrow-up.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-up-circle",
    path: path.join(__dirname, "../icons/arrow-up-circle.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-up-left",
    path: path.join(__dirname, "../icons/arrow-up-left.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-up-on-square",
    path: path.join(__dirname, "../icons/arrow-up-on-square.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-up-on-square-stack",
    path: path.join(__dirname, "../icons/arrow-up-on-square-stack.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-up-right",
    path: path.join(__dirname, "../icons/arrow-up-right.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-up-tray",
    path: path.join(__dirname, "../icons/arrow-up-tray.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-uturn-down",
    path: path.join(__dirname, "../icons/arrow-uturn-down.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-uturn-left",
    path: path.join(__dirname, "../icons/arrow-uturn-left.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-uturn-right",
    path: path.join(__dirname, "../icons/arrow-uturn-right.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrow-uturn-up",
    path: path.join(__dirname, "../icons/arrow-uturn-up.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrows-pointing-in",
    path: path.join(__dirname, "../icons/arrows-pointing-in.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrows-pointing-out",
    path: path.join(__dirname, "../icons/arrows-pointing-out.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrows-right-left",
    path: path.join(__dirname, "../icons/arrows-right-left.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "arrows-up-down",
    path: path.join(__dirname, "../icons/arrows-up-down.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "at-symbol",
    path: path.join(__dirname, "../icons/at-symbol.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "backspace",
    path: path.join(__dirname, "../icons/backspace.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "backward",
    path: path.join(__dirname, "../icons/backward.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "banknotes",
    path: path.join(__dirname, "../icons/banknotes.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "bars-2",
    path: path.join(__dirname, "../icons/bars2.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "bars-3",
    path: path.join(__dirname, "../icons/bars3.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "bars-3-bottom-left",
    path: path.join(__dirname, "../icons/bars3-bottom-left.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "bars-3-bottom-right",
    path: path.join(__dirname, "../icons/bars3-bottom-right.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "bars-3-center-left",
    path: path.join(__dirname, "../icons/bars3-center-left.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "bars-4",
    path: path.join(__dirname, "../icons/bars4.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "bars-arrow-down",
    path: path.join(__dirname, "../icons/bars-arrow-down.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "bars-arrow-up",
    path: path.join(__dirname, "../icons/bars-arrow-up.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "battery-0",
    path: path.join(__dirname, "../icons/battery0.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "battery-100",
    path: path.join(__dirname, "../icons/battery100.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "battery-50",
    path: path.join(__dirname, "../icons/battery50.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "beaker",
    path: path.join(__dirname, "../icons/beaker.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "bell",
    path: path.join(__dirname, "../icons/bell.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "bell-alert",
    path: path.join(__dirname, "../icons/bell-alert.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "bell-slash",
    path: path.join(__dirname, "../icons/bell-slash.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "bell-snooze",
    path: path.join(__dirname, "../icons/bell-snooze.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "bold",
    path: path.join(__dirname, "../icons/bold.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "bolt",
    path: path.join(__dirname, "../icons/bolt.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "bolt-slash",
    path: path.join(__dirname, "../icons/bolt-slash.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "book-open",
    path: path.join(__dirname, "../icons/book-open.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "bookmark",
    path: path.join(__dirname, "../icons/bookmark.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "bookmark-slash",
    path: path.join(__dirname, "../icons/bookmark-slash.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "bookmark-square",
    path: path.join(__dirname, "../icons/bookmark-square.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "briefcase",
    path: path.join(__dirname, "../icons/briefcase.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "bug-ant",
    path: path.join(__dirname, "../icons/bug-ant.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "building-library",
    path: path.join(__dirname, "../icons/building-library.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "building-office",
    path: path.join(__dirname, "../icons/building-office.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "building-office-2",
    path: path.join(__dirname, "../icons/building-office2.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "building-storefront",
    path: path.join(__dirname, "../icons/building-storefront.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "cake",
    path: path.join(__dirname, "../icons/cake.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "calculator",
    path: path.join(__dirname, "../icons/calculator.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "calendar",
    path: path.join(__dirname, "../icons/calendar.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "calendar-date-range",
    path: path.join(__dirname, "../icons/calendar-date-range.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "calendar-days",
    path: path.join(__dirname, "../icons/calendar-days.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "camera",
    path: path.join(__dirname, "../icons/camera.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "chart-bar",
    path: path.join(__dirname, "../icons/chart-bar.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "chart-bar-square",
    path: path.join(__dirname, "../icons/chart-bar-square.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "chart-pie",
    path: path.join(__dirname, "../icons/chart-pie.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "chat-bubble-bottom-center",
    path: path.join(__dirname, "../icons/chat-bubble-bottom-center.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "chat-bubble-bottom-center-text",
    path: path.join(__dirname, "../icons/chat-bubble-bottom-center-text.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "chat-bubble-left",
    path: path.join(__dirname, "../icons/chat-bubble-left.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "chat-bubble-left-ellipsis",
    path: path.join(__dirname, "../icons/chat-bubble-left-ellipsis.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "chat-bubble-left-right",
    path: path.join(__dirname, "../icons/chat-bubble-left-right.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "chat-bubble-oval-left",
    path: path.join(__dirname, "../icons/chat-bubble-oval-left.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "chat-bubble-oval-left-ellipsis",
    path: path.join(__dirname, "../icons/chat-bubble-oval-left-ellipsis.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "check",
    path: path.join(__dirname, "../icons/check.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "check-badge",
    path: path.join(__dirname, "../icons/check-badge.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "check-circle",
    path: path.join(__dirname, "../icons/check-circle.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "chevron-double-down",
    path: path.join(__dirname, "../icons/chevron-double-down.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "chevron-double-left",
    path: path.join(__dirname, "../icons/chevron-double-left.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "chevron-double-right",
    path: path.join(__dirname, "../icons/chevron-double-right.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "chevron-double-up",
    path: path.join(__dirname, "../icons/chevron-double-up.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "chevron-down",
    path: path.join(__dirname, "../icons/chevron-down.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "chevron-left",
    path: path.join(__dirname, "../icons/chevron-left.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "chevron-right",
    path: path.join(__dirname, "../icons/chevron-right.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "chevron-up",
    path: path.join(__dirname, "../icons/chevron-up.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "chevron-up-down",
    path: path.join(__dirname, "../icons/chevron-up-down.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "circle-stack",
    path: path.join(__dirname, "../icons/circle-stack.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "clipboard",
    path: path.join(__dirname, "../icons/clipboard.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "clipboard-document",
    path: path.join(__dirname, "../icons/clipboard-document.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "clipboard-document-check",
    path: path.join(__dirname, "../icons/clipboard-document-check.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "clipboard-document-list",
    path: path.join(__dirname, "../icons/clipboard-document-list.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "clock",
    path: path.join(__dirname, "../icons/clock.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "cloud",
    path: path.join(__dirname, "../icons/cloud.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "cloud-arrow-down",
    path: path.join(__dirname, "../icons/cloud-arrow-down.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "cloud-arrow-up",
    path: path.join(__dirname, "../icons/cloud-arrow-up.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "code-bracket",
    path: path.join(__dirname, "../icons/code-bracket.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "code-bracket-square",
    path: path.join(__dirname, "../icons/code-bracket-square.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "cog",
    path: path.join(__dirname, "../icons/cog.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "cog-6-tooth",
    path: path.join(__dirname, "../icons/cog6-tooth.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "cog-8-tooth",
    path: path.join(__dirname, "../icons/cog8-tooth.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "command-line",
    path: path.join(__dirname, "../icons/command-line.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "computer-desktop",
    path: path.join(__dirname, "../icons/computer-desktop.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "cpu-chip",
    path: path.join(__dirname, "../icons/cpu-chip.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "credit-card",
    path: path.join(__dirname, "../icons/credit-card.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "cube",
    path: path.join(__dirname, "../icons/cube.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "cube-transparent",
    path: path.join(__dirname, "../icons/cube-transparent.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "currency-bangladeshi",
    path: path.join(__dirname, "../icons/currency-bangladeshi.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "currency-dollar",
    path: path.join(__dirname, "../icons/currency-dollar.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "currency-euro",
    path: path.join(__dirname, "../icons/currency-euro.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "currency-pound",
    path: path.join(__dirname, "../icons/currency-pound.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "currency-rupee",
    path: path.join(__dirname, "../icons/currency-rupee.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "currency-yen",
    path: path.join(__dirname, "../icons/currency-yen.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "cursor-arrow-rays",
    path: path.join(__dirname, "../icons/cursor-arrow-rays.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "cursor-arrow-ripple",
    path: path.join(__dirname, "../icons/cursor-arrow-ripple.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "device-phone-mobile",
    path: path.join(__dirname, "../icons/device-phone-mobile.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "device-tablet",
    path: path.join(__dirname, "../icons/device-tablet.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "divide",
    path: path.join(__dirname, "../icons/divide.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "document",
    path: path.join(__dirname, "../icons/document.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "document-arrow-down",
    path: path.join(__dirname, "../icons/document-arrow-down.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "document-arrow-up",
    path: path.join(__dirname, "../icons/document-arrow-up.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "document-chart-bar",
    path: path.join(__dirname, "../icons/document-chart-bar.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "document-check",
    path: path.join(__dirname, "../icons/document-check.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "document-currency-bangladeshi",
    path: path.join(__dirname, "../icons/document-currency-bangladeshi.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "document-currency-dollar",
    path: path.join(__dirname, "../icons/document-currency-dollar.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "document-currency-euro",
    path: path.join(__dirname, "../icons/document-currency-euro.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "document-currency-pound",
    path: path.join(__dirname, "../icons/document-currency-pound.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "document-currency-rupee",
    path: path.join(__dirname, "../icons/document-currency-rupee.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "document-currency-yen",
    path: path.join(__dirname, "../icons/document-currency-yen.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "document-duplicate",
    path: path.join(__dirname, "../icons/document-duplicate.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "document-magnifying-glass",
    path: path.join(__dirname, "../icons/document-magnifying-glass.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "document-minus",
    path: path.join(__dirname, "../icons/document-minus.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "document-plus",
    path: path.join(__dirname, "../icons/document-plus.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "document-text",
    path: path.join(__dirname, "../icons/document-text.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "ellipsis-horizontal",
    path: path.join(__dirname, "../icons/ellipsis-horizontal.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "ellipsis-horizontal-circle",
    path: path.join(__dirname, "../icons/ellipsis-horizontal-circle.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "ellipsis-vertical",
    path: path.join(__dirname, "../icons/ellipsis-vertical.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "envelope",
    path: path.join(__dirname, "../icons/envelope.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "envelope-open",
    path: path.join(__dirname, "../icons/envelope-open.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "equals",
    path: path.join(__dirname, "../icons/equals.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "exclamation-circle",
    path: path.join(__dirname, "../icons/exclamation-circle.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "exclamation-triangle",
    path: path.join(__dirname, "../icons/exclamation-triangle.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "eye",
    path: path.join(__dirname, "../icons/eye.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "eye-dropper",
    path: path.join(__dirname, "../icons/eye-dropper.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "eye-slash",
    path: path.join(__dirname, "../icons/eye-slash.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "face-frown",
    path: path.join(__dirname, "../icons/face-frown.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "face-smile",
    path: path.join(__dirname, "../icons/face-smile.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "film",
    path: path.join(__dirname, "../icons/film.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "finger-print",
    path: path.join(__dirname, "../icons/finger-print.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "fire",
    path: path.join(__dirname, "../icons/fire.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "flag",
    path: path.join(__dirname, "../icons/flag.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "folder",
    path: path.join(__dirname, "../icons/folder.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "folder-arrow-down",
    path: path.join(__dirname, "../icons/folder-arrow-down.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "folder-minus",
    path: path.join(__dirname, "../icons/folder-minus.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "folder-open",
    path: path.join(__dirname, "../icons/folder-open.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "folder-plus",
    path: path.join(__dirname, "../icons/folder-plus.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "forward",
    path: path.join(__dirname, "../icons/forward.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "funnel",
    path: path.join(__dirname, "../icons/funnel.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "gif",
    path: path.join(__dirname, "../icons/gif.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "gift",
    path: path.join(__dirname, "../icons/gift.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "gift-top",
    path: path.join(__dirname, "../icons/gift-top.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "globe-alt",
    path: path.join(__dirname, "../icons/globe-alt.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "globe-americas",
    path: path.join(__dirname, "../icons/globe-americas.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "globe-asia-australia",
    path: path.join(__dirname, "../icons/globe-asia-australia.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "globe-europe-africa",
    path: path.join(__dirname, "../icons/globe-europe-africa.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "h1",
    path: path.join(__dirname, "../icons/h1.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "h2",
    path: path.join(__dirname, "../icons/h2.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "h3",
    path: path.join(__dirname, "../icons/h3.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "hand-raised",
    path: path.join(__dirname, "../icons/hand-raised.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "hand-thumb-down",
    path: path.join(__dirname, "../icons/hand-thumb-down.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "hand-thumb-up",
    path: path.join(__dirname, "../icons/hand-thumb-up.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "hashtag",
    path: path.join(__dirname, "../icons/hashtag.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "heart",
    path: path.join(__dirname, "../icons/heart.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "home",
    path: path.join(__dirname, "../icons/home.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "home-modern",
    path: path.join(__dirname, "../icons/home-modern.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "identification",
    path: path.join(__dirname, "../icons/identification.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "inbox",
    path: path.join(__dirname, "../icons/inbox.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "inbox-arrow-down",
    path: path.join(__dirname, "../icons/inbox-arrow-down.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "inbox-stack",
    path: path.join(__dirname, "../icons/inbox-stack.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "information-circle",
    path: path.join(__dirname, "../icons/information-circle.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "italic",
    path: path.join(__dirname, "../icons/italic.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "key",
    path: path.join(__dirname, "../icons/key.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "language",
    path: path.join(__dirname, "../icons/language.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "lifebuoy",
    path: path.join(__dirname, "../icons/lifebuoy.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "light-bulb",
    path: path.join(__dirname, "../icons/light-bulb.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "link",
    path: path.join(__dirname, "../icons/link.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "link-slash",
    path: path.join(__dirname, "../icons/link-slash.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "list-bullet",
    path: path.join(__dirname, "../icons/list-bullet.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "lock-closed",
    path: path.join(__dirname, "../icons/lock-closed.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "lock-open",
    path: path.join(__dirname, "../icons/lock-open.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "magnifying-glass",
    path: path.join(__dirname, "../icons/magnifying-glass.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "magnifying-glass-circle",
    path: path.join(__dirname, "../icons/magnifying-glass-circle.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "magnifying-glass-minus",
    path: path.join(__dirname, "../icons/magnifying-glass-minus.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "magnifying-glass-plus",
    path: path.join(__dirname, "../icons/magnifying-glass-plus.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "map",
    path: path.join(__dirname, "../icons/map.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "map-pin",
    path: path.join(__dirname, "../icons/map-pin.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "megaphone",
    path: path.join(__dirname, "../icons/megaphone.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "microphone",
    path: path.join(__dirname, "../icons/microphone.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "minus",
    path: path.join(__dirname, "../icons/minus.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "minus-circle",
    path: path.join(__dirname, "../icons/minus-circle.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "minus-small",
    path: path.join(__dirname, "../icons/minus-small.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "moon",
    path: path.join(__dirname, "../icons/moon.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "musical-note",
    path: path.join(__dirname, "../icons/musical-note.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "newspaper",
    path: path.join(__dirname, "../icons/newspaper.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "no-symbol",
    path: path.join(__dirname, "../icons/no-symbol.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "numbered-list",
    path: path.join(__dirname, "../icons/numbered-list.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "paint-brush",
    path: path.join(__dirname, "../icons/paint-brush.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "paper-airplane",
    path: path.join(__dirname, "../icons/paper-airplane.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "paper-clip",
    path: path.join(__dirname, "../icons/paper-clip.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "pause",
    path: path.join(__dirname, "../icons/pause.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "pause-circle",
    path: path.join(__dirname, "../icons/pause-circle.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "pencil",
    path: path.join(__dirname, "../icons/pencil.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "pencil-square",
    path: path.join(__dirname, "../icons/pencil-square.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "percent-badge",
    path: path.join(__dirname, "../icons/percent-badge.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "phone",
    path: path.join(__dirname, "../icons/phone.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "phone-arrow-down-left",
    path: path.join(__dirname, "../icons/phone-arrow-down-left.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "phone-arrow-up-right",
    path: path.join(__dirname, "../icons/phone-arrow-up-right.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "phone-x-mark",
    path: path.join(__dirname, "../icons/phone-x-mark.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "photo",
    path: path.join(__dirname, "../icons/photo.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "play",
    path: path.join(__dirname, "../icons/play.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "play-circle",
    path: path.join(__dirname, "../icons/play-circle.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "play-pause",
    path: path.join(__dirname, "../icons/play-pause.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "plus",
    path: path.join(__dirname, "../icons/plus.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "plus-circle",
    path: path.join(__dirname, "../icons/plus-circle.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "plus-small",
    path: path.join(__dirname, "../icons/plus-small.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "power",
    path: path.join(__dirname, "../icons/power.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "presentation-chart-bar",
    path: path.join(__dirname, "../icons/presentation-chart-bar.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "presentation-chart-line",
    path: path.join(__dirname, "../icons/presentation-chart-line.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "printer",
    path: path.join(__dirname, "../icons/printer.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "puzzle-piece",
    path: path.join(__dirname, "../icons/puzzle-piece.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "qr-code",
    path: path.join(__dirname, "../icons/qr-code.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "question-mark-circle",
    path: path.join(__dirname, "../icons/question-mark-circle.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "queue-list",
    path: path.join(__dirname, "../icons/queue-list.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "radio",
    path: path.join(__dirname, "../icons/radio.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "receipt-percent",
    path: path.join(__dirname, "../icons/receipt-percent.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "receipt-refund",
    path: path.join(__dirname, "../icons/receipt-refund.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "rectangle-group",
    path: path.join(__dirname, "../icons/rectangle-group.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "rectangle-stack",
    path: path.join(__dirname, "../icons/rectangle-stack.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "rocket-launch",
    path: path.join(__dirname, "../icons/rocket-launch.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "rss",
    path: path.join(__dirname, "../icons/rss.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "scale",
    path: path.join(__dirname, "../icons/scale.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "scissors",
    path: path.join(__dirname, "../icons/scissors.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "server",
    path: path.join(__dirname, "../icons/server.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "server-stack",
    path: path.join(__dirname, "../icons/server-stack.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "share",
    path: path.join(__dirname, "../icons/share.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "shield-check",
    path: path.join(__dirname, "../icons/shield-check.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "shield-exclamation",
    path: path.join(__dirname, "../icons/shield-exclamation.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "shopping-bag",
    path: path.join(__dirname, "../icons/shopping-bag.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "shopping-cart",
    path: path.join(__dirname, "../icons/shopping-cart.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "signal",
    path: path.join(__dirname, "../icons/signal.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "signal-slash",
    path: path.join(__dirname, "../icons/signal-slash.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "slash",
    path: path.join(__dirname, "../icons/slash.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "sparkles",
    path: path.join(__dirname, "../icons/sparkles.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "speaker-wave",
    path: path.join(__dirname, "../icons/speaker-wave.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "speaker-x-mark",
    path: path.join(__dirname, "../icons/speaker-x-mark.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "square-2-stack",
    path: path.join(__dirname, "../icons/square2-stack.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "squares-plus",
    path: path.join(__dirname, "../icons/squares-plus.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "star",
    path: path.join(__dirname, "../icons/star.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "stop",
    path: path.join(__dirname, "../icons/stop.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "stop-circle",
    path: path.join(__dirname, "../icons/stop-circle.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "strikethrough",
    path: path.join(__dirname, "../icons/strikethrough.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "sun",
    path: path.join(__dirname, "../icons/sun.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "swatch",
    path: path.join(__dirname, "../icons/swatch.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "table-cells",
    path: path.join(__dirname, "../icons/table-cells.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "tag",
    path: path.join(__dirname, "../icons/tag.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "ticket",
    path: path.join(__dirname, "../icons/ticket.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "trash",
    path: path.join(__dirname, "../icons/trash.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "trophy",
    path: path.join(__dirname, "../icons/trophy.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "truck",
    path: path.join(__dirname, "../icons/truck.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "tv",
    path: path.join(__dirname, "../icons/tv.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "underline",
    path: path.join(__dirname, "../icons/underline.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "user",
    path: path.join(__dirname, "../icons/user.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "user-circle",
    path: path.join(__dirname, "../icons/user-circle.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "user-group",
    path: path.join(__dirname, "../icons/user-group.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "user-minus",
    path: path.join(__dirname, "../icons/user-minus.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "user-plus",
    path: path.join(__dirname, "../icons/user-plus.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "users",
    path: path.join(__dirname, "../icons/users.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "variable",
    path: path.join(__dirname, "../icons/variable.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "video-camera",
    path: path.join(__dirname, "../icons/video-camera.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "video-camera-slash",
    path: path.join(__dirname, "../icons/video-camera-slash.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "view-columns",
    path: path.join(__dirname, "../icons/view-columns.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "viewfinder-circle",
    path: path.join(__dirname, "../icons/viewfinder-circle.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
  {
    name: "wallet",
    path: path.join(__dirname, "../icons/wallet.tsx"),
    registryDependencies: [],
    dependencies: ["motion"],
  },
];
